-- MySQL Script generated by MySQL Workbench
-- 08/15/18 20:05:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trade` DEFAULT CHARACTER SET utf8 ;
USE `trade` ;

-- -----------------------------------------------------
-- Table `trade`.`trade_code`
-- -----------------------------------------------------
CREATE TABLE `trade_code` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(45) DEFAULT NULL COMMENT '兑换码',
  `password` varchar(45) DEFAULT NULL COMMENT '密码',
  `type` tinyint(1) DEFAULT '0' COMMENT '类型 0- 生态茉莉龙豪礼盒   1-生态福鼎白茶小锡罐礼盒  2-生态特级手制铁观音小锡罐礼盒',
  `status` tinyint(1) DEFAULT NULL COMMENT '状态 0 - 未兑换 1-已兑换',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `token` varchar(40) DEFAULT NULL COMMENT '令牌',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='兑换码表';


-- -----------------------------------------------------
-- Table `trade`.`trade_info`
-- -----------------------------------------------------
CREATE TABLE `trade_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(45) DEFAULT NULL COMMENT '用户名',
  `telephone` varchar(45) DEFAULT NULL COMMENT '电话',
  `address` varchar(45) DEFAULT NULL COMMENT '地址',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='交易信息表';


-- -----------------------------------------------------
-- Table `trade`.`code_info_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `code_info_relation`;
CREATE TABLE `code_info_relation` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `trade_code_id` int(11) DEFAULT NULL COMMENT '兑换码id',
  `trade_info_id` int(11) DEFAULT NULL COMMENT '交易信息id',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '兑换时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='关系表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
